// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for createDiagnosticJob operation.
    /// </summary>
    public partial class CreateDiagnosticJobHeaders
    {
        /// <summary>
        /// Initializes a new instance of the CreateDiagnosticJobHeaders class.
        /// </summary>
        public CreateDiagnosticJobHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateDiagnosticJobHeaders class.
        /// </summary>
        /// <param name="location">the url for the newly created job</param>
        public CreateDiagnosticJobHeaders(string location = default(string))
        {
            Location = location;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the url for the newly created job
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

    }
}
