// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DiagnoticTest
    {
        /// <summary>
        /// Initializes a new instance of the DiagnoticTest class.
        /// </summary>
        public DiagnoticTest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DiagnoticTest class.
        /// </summary>
        public DiagnoticTest(string category = default(string), string name = default(string), string description = default(string), IList<object> parameters = default(IList<object>), IList<object> arguments = default(IList<object>))
        {
            Category = category;
            Name = name;
            Description = description;
            Parameters = parameters;
            Arguments = arguments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameters")]
        public IList<object> Parameters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "arguments")]
        public IList<object> Arguments { get; set; }

    }
}
