// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MetricsValuesItem
    {
        /// <summary>
        /// Initializes a new instance of the MetricsValuesItem class.
        /// </summary>
        public MetricsValuesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MetricsValuesItem class.
        /// </summary>
        /// <param name="node">Node name</param>
        /// <param name="data">Node metric data</param>
        public MetricsValuesItem(string node = default(string), IDictionary<string, double?> data = default(IDictionary<string, double?>))
        {
            Node = node;
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets node name
        /// </summary>
        [JsonProperty(PropertyName = "node")]
        public string Node { get; set; }

        /// <summary>
        /// Gets or sets node metric data
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IDictionary<string, double?> Data { get; set; }

    }
}
