// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NodeMetadataCompute
    {
        /// <summary>
        /// Initializes a new instance of the NodeMetadataCompute class.
        /// </summary>
        public NodeMetadataCompute()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeMetadataCompute class.
        /// </summary>
        /// <param name="location">Azure Region the VM is running in</param>
        /// <param name="name">Name of the VM</param>
        /// <param name="offer">Offer information for the VM image. This value
        /// is only present for images deployed from Azure image
        /// gallery.</param>
        /// <param name="osType">Linux or Windows</param>
        /// <param name="platformFaultDomain">Fault domain the VM is running
        /// in</param>
        /// <param name="platformUpdateDomain">Update domain the VM is running
        /// in</param>
        /// <param name="publisher">Publisher of the VM image</param>
        /// <param name="sku">Specific SKU for the VM image</param>
        /// <param name="version">Version of the VM image</param>
        /// <param name="vmId">Unique identifier for the VM</param>
        /// <param name="vmSize">VM size</param>
        /// <param name="subscriptionId">Azure subscription for the Virtual
        /// Machine</param>
        /// <param name="tags">Tags for your Virtual Machine</param>
        /// <param name="resourceGroupName">Resource group for your Virtual
        /// Machine</param>
        /// <param name="placementGroupId">Placement Group of your virtual
        /// machine scale set</param>
        public NodeMetadataCompute(string location = default(string), string name = default(string), string offer = default(string), string osType = default(string), string platformFaultDomain = default(string), string platformUpdateDomain = default(string), string publisher = default(string), string sku = default(string), string version = default(string), string vmId = default(string), string vmSize = default(string), string subscriptionId = default(string), string tags = default(string), string resourceGroupName = default(string), string placementGroupId = default(string))
        {
            Location = location;
            Name = name;
            Offer = offer;
            OsType = osType;
            PlatformFaultDomain = platformFaultDomain;
            PlatformUpdateDomain = platformUpdateDomain;
            Publisher = publisher;
            Sku = sku;
            Version = version;
            VmId = vmId;
            VmSize = vmSize;
            SubscriptionId = subscriptionId;
            Tags = tags;
            ResourceGroupName = resourceGroupName;
            PlacementGroupId = placementGroupId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets azure Region the VM is running in
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or sets name of the VM
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets offer information for the VM image. This value is only
        /// present for images deployed from Azure image gallery.
        /// </summary>
        [JsonProperty(PropertyName = "offer")]
        public string Offer { get; set; }

        /// <summary>
        /// Gets or sets linux or Windows
        /// </summary>
        [JsonProperty(PropertyName = "osType")]
        public string OsType { get; set; }

        /// <summary>
        /// Gets or sets fault domain the VM is running in
        /// </summary>
        [JsonProperty(PropertyName = "platformFaultDomain")]
        public string PlatformFaultDomain { get; set; }

        /// <summary>
        /// Gets or sets update domain the VM is running in
        /// </summary>
        [JsonProperty(PropertyName = "platformUpdateDomain")]
        public string PlatformUpdateDomain { get; set; }

        /// <summary>
        /// Gets or sets publisher of the VM image
        /// </summary>
        [JsonProperty(PropertyName = "publisher")]
        public string Publisher { get; set; }

        /// <summary>
        /// Gets or sets specific SKU for the VM image
        /// </summary>
        [JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }

        /// <summary>
        /// Gets or sets version of the VM image
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

        /// <summary>
        /// Gets or sets unique identifier for the VM
        /// </summary>
        [JsonProperty(PropertyName = "vmId")]
        public string VmId { get; set; }

        /// <summary>
        /// Gets or sets VM size
        /// </summary>
        [JsonProperty(PropertyName = "vmSize")]
        public string VmSize { get; set; }

        /// <summary>
        /// Gets or sets azure subscription for the Virtual Machine
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// Gets or sets tags for your Virtual Machine
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public string Tags { get; set; }

        /// <summary>
        /// Gets or sets resource group for your Virtual Machine
        /// </summary>
        [JsonProperty(PropertyName = "resourceGroupName")]
        public string ResourceGroupName { get; set; }

        /// <summary>
        /// Gets or sets placement Group of your virtual machine scale set
        /// </summary>
        [JsonProperty(PropertyName = "placementGroupId")]
        public string PlacementGroupId { get; set; }

    }
}
