// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NodeMetadataNetworkInterfaceItemIpv4
    {
        /// <summary>
        /// Initializes a new instance of the
        /// NodeMetadataNetworkInterfaceItemIpv4 class.
        /// </summary>
        public NodeMetadataNetworkInterfaceItemIpv4()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// NodeMetadataNetworkInterfaceItemIpv4 class.
        /// </summary>
        public NodeMetadataNetworkInterfaceItemIpv4(IList<NodeMetadataNetworkInterfaceItemIpv4IpAddressItem> ipAddress = default(IList<NodeMetadataNetworkInterfaceItemIpv4IpAddressItem>), IList<NodeMetadataNetworkInterfaceItemIpv4SubnetItem> subnet = default(IList<NodeMetadataNetworkInterfaceItemIpv4SubnetItem>))
        {
            IpAddress = ipAddress;
            Subnet = subnet;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipAddress")]
        public IList<NodeMetadataNetworkInterfaceItemIpv4IpAddressItem> IpAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subnet")]
        public IList<NodeMetadataNetworkInterfaceItemIpv4SubnetItem> Subnet { get; set; }

    }
}
