// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NodeMetadata
    {
        /// <summary>
        /// Initializes a new instance of the NodeMetadata class.
        /// </summary>
        public NodeMetadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeMetadata class.
        /// </summary>
        public NodeMetadata(NodeMetadataCompute compute = default(NodeMetadataCompute), NodeMetadataNetwork network = default(NodeMetadataNetwork))
        {
            Compute = compute;
            Network = network;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "compute")]
        public NodeMetadataCompute Compute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "network")]
        public NodeMetadataNetwork Network { get; set; }

    }
}
