// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NodeMetadataNetworkInterfaceItemIpv6
    {
        /// <summary>
        /// Initializes a new instance of the
        /// NodeMetadataNetworkInterfaceItemIpv6 class.
        /// </summary>
        public NodeMetadataNetworkInterfaceItemIpv6()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// NodeMetadataNetworkInterfaceItemIpv6 class.
        /// </summary>
        public NodeMetadataNetworkInterfaceItemIpv6(IList<string> ipAddress = default(IList<string>))
        {
            IpAddress = ipAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipAddress")]
        public IList<string> IpAddress { get; set; }

    }
}
