// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NodeNetwork
    {
        /// <summary>
        /// Initializes a new instance of the NodeNetwork class.
        /// </summary>
        public NodeNetwork()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeNetwork class.
        /// </summary>
        public NodeNetwork(string name = default(string), string macAddress = default(string), string ipV4 = default(string), string ipV6 = default(string), bool? isIB = default(bool?))
        {
            Name = name;
            MacAddress = macAddress;
            IpV4 = ipV4;
            IpV6 = ipV6;
            IsIB = isIB;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "macAddress")]
        public string MacAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipV4")]
        public string IpV4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipV6")]
        public string IpV6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isIB")]
        public bool? IsIB { get; set; }

    }
}
