// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NodeSummary
    {
        /// <summary>
        /// Initializes a new instance of the NodeSummary class.
        /// </summary>
        public NodeSummary()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeSummary class.
        /// </summary>
        public NodeSummary(System.DateTime? lastUpdated = default(System.DateTime?), IDictionary<string, double?> data = default(IDictionary<string, double?>))
        {
            LastUpdated = lastUpdated;
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastUpdated")]
        public System.DateTime? LastUpdated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IDictionary<string, double?> Data { get; set; }

    }
}
