// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NodeMetadataNetworkInterfaceItemIpv4IpAddressItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// NodeMetadataNetworkInterfaceItemIpv4IpAddressItem class.
        /// </summary>
        public NodeMetadataNetworkInterfaceItemIpv4IpAddressItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// NodeMetadataNetworkInterfaceItemIpv4IpAddressItem class.
        /// </summary>
        public NodeMetadataNetworkInterfaceItemIpv4IpAddressItem(string privateIpAddress = default(string), string publicIpAddress = default(string))
        {
            PrivateIpAddress = privateIpAddress;
            PublicIpAddress = publicIpAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "privateIpAddress")]
        public string PrivateIpAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publicIpAddress")]
        public string PublicIpAddress { get; set; }

    }
}
