// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NodeJob
    {
        /// <summary>
        /// Initializes a new instance of the NodeJob class.
        /// </summary>
        public NodeJob()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeJob class.
        /// </summary>
        public NodeJob(int? jobId = default(int?), TaskResult tasks = default(TaskResult))
        {
            JobId = jobId;
            Tasks = tasks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "jobId")]
        public int? JobId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tasks")]
        public TaskResult Tasks { get; set; }

    }
}
