// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NodeMetadataNetworkInterfaceItem
    {
        /// <summary>
        /// Initializes a new instance of the NodeMetadataNetworkInterfaceItem
        /// class.
        /// </summary>
        public NodeMetadataNetworkInterfaceItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeMetadataNetworkInterfaceItem
        /// class.
        /// </summary>
        public NodeMetadataNetworkInterfaceItem(NodeMetadataNetworkInterfaceItemIpv4 ipv4 = default(NodeMetadataNetworkInterfaceItemIpv4), NodeMetadataNetworkInterfaceItemIpv6 ipv6 = default(NodeMetadataNetworkInterfaceItemIpv6), string macAddress = default(string))
        {
            Ipv4 = ipv4;
            Ipv6 = ipv6;
            MacAddress = macAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipv4")]
        public NodeMetadataNetworkInterfaceItemIpv4 Ipv4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipv6")]
        public NodeMetadataNetworkInterfaceItemIpv6 Ipv6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "macAddress")]
        public string MacAddress { get; set; }

    }
}
