// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NodeMetricsDataItemMetricItemsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// NodeMetricsDataItemMetricItemsItem class.
        /// </summary>
        public NodeMetricsDataItemMetricItemsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// NodeMetricsDataItemMetricItemsItem class.
        /// </summary>
        /// <param name="category">Metric category</param>
        /// <param name="instanceValues">Metric data</param>
        public NodeMetricsDataItemMetricItemsItem(string category = default(string), IDictionary<string, double?> instanceValues = default(IDictionary<string, double?>))
        {
            Category = category;
            InstanceValues = instanceValues;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets metric category
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// Gets or sets metric data
        /// </summary>
        [JsonProperty(PropertyName = "instanceValues")]
        public IDictionary<string, double?> InstanceValues { get; set; }

    }
}
