// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NodeGpu
    {
        /// <summary>
        /// Initializes a new instance of the NodeGpu class.
        /// </summary>
        public NodeGpu()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeGpu class.
        /// </summary>
        public NodeGpu(string name = default(string), string uuid = default(string), string pciBusDevice = default(string), string pciBusId = default(string), int? totalMemory = default(int?), int? maxSMClock = default(int?))
        {
            Name = name;
            Uuid = uuid;
            PciBusDevice = pciBusDevice;
            PciBusId = pciBusId;
            TotalMemory = totalMemory;
            MaxSMClock = maxSMClock;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uuid")]
        public string Uuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pciBusDevice")]
        public string PciBusDevice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pciBusId")]
        public string PciBusId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalMemory")]
        public int? TotalMemory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxSMClock")]
        public int? MaxSMClock { get; set; }

    }
}
