// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ScheduledEvent
    {
        /// <summary>
        /// Initializes a new instance of the ScheduledEvent class.
        /// </summary>
        public ScheduledEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ScheduledEvent class.
        /// </summary>
        /// <param name="eventId">Globally unique identifier for this
        /// event</param>
        /// <param name="eventType">Impact this event causes. Possible values
        /// include: 'Freeze', 'Reboot', 'Redeploy'</param>
        /// <param name="resourceType">Type of resource this event impacts.
        /// Possible values include: 'VirtualMachine'</param>
        /// <param name="resources">List of resources this event impacts. This
        /// is guaranteed to contain machines from at most one Update Domain,
        /// but may not contain all machines in the UD.</param>
        /// <param name="eventStatus">No Completed or similar status is ever
        /// provided; the event will no longer be returned when the event is
        /// completed. Possible values include: 'Scheduled', 'Started'</param>
        /// <param name="notBefore">Time after which this event may
        /// start</param>
        public ScheduledEvent(string eventId = default(string), string eventType = default(string), string resourceType = default(string), IList<string> resources = default(IList<string>), string eventStatus = default(string), System.DateTime? notBefore = default(System.DateTime?))
        {
            EventId = eventId;
            EventType = eventType;
            ResourceType = resourceType;
            Resources = resources;
            EventStatus = eventStatus;
            NotBefore = notBefore;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets globally unique identifier for this event
        /// </summary>
        [JsonProperty(PropertyName = "eventId")]
        public string EventId { get; set; }

        /// <summary>
        /// Gets or sets impact this event causes. Possible values include:
        /// 'Freeze', 'Reboot', 'Redeploy'
        /// </summary>
        [JsonProperty(PropertyName = "eventType")]
        public string EventType { get; set; }

        /// <summary>
        /// Gets or sets type of resource this event impacts. Possible values
        /// include: 'VirtualMachine'
        /// </summary>
        [JsonProperty(PropertyName = "resourceType")]
        public string ResourceType { get; set; }

        /// <summary>
        /// Gets or sets list of resources this event impacts. This is
        /// guaranteed to contain machines from at most one Update Domain, but
        /// may not contain all machines in the UD.
        /// </summary>
        [JsonProperty(PropertyName = "resources")]
        public IList<string> Resources { get; set; }

        /// <summary>
        /// Gets or sets no Completed or similar status is ever provided; the
        /// event will no longer be returned when the event is completed.
        /// Possible values include: 'Scheduled', 'Started'
        /// </summary>
        [JsonProperty(PropertyName = "eventStatus")]
        public string EventStatus { get; set; }

        /// <summary>
        /// Gets or sets time after which this event may start
        /// </summary>
        [JsonProperty(PropertyName = "notBefore")]
        public System.DateTime? NotBefore { get; set; }

    }
}
