// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ScheduledEvents
    {
        /// <summary>
        /// Initializes a new instance of the ScheduledEvents class.
        /// </summary>
        public ScheduledEvents()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ScheduledEvents class.
        /// </summary>
        public ScheduledEvents(int? documentIncarnation = default(int?), IList<ScheduledEvent> events = default(IList<ScheduledEvent>))
        {
            DocumentIncarnation = documentIncarnation;
            Events = events;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentIncarnation")]
        public int? DocumentIncarnation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "events")]
        public IList<ScheduledEvent> Events { get; set; }

    }
}
