// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HPC.ACM.API
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for HPCWebAPI.
    /// </summary>
    public static partial class HPCWebAPIExtensions
    {
            /// <summary>
            /// Get a list of nodes
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='lastId'>
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            public static IList<Node> GetNodes(this IHPCWebAPI operations, string lastId = default(string), int? count = 1000)
            {
                return operations.GetNodesAsync(lastId, count).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a list of nodes
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='lastId'>
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Node>> GetNodesAsync(this IHPCWebAPI operations, string lastId = default(string), int? count = 1000, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetNodesWithHttpMessagesAsync(lastId, count, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            public static Node GetNode(this IHPCWebAPI operations, string id)
            {
                return operations.GetNodeAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Node> GetNodeAsync(this IHPCWebAPI operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetNodeWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// get metadata of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            public static NodeMetadata GetNodeMetadata(this IHPCWebAPI operations, string id)
            {
                return operations.GetNodeMetadataAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// get metadata of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<NodeMetadata> GetNodeMetadataAsync(this IHPCWebAPI operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetNodeMetadataWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// get scheduled events of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            public static ScheduledEvents GetNodeScheduledEvents(this IHPCWebAPI operations, string id)
            {
                return operations.GetNodeScheduledEventsAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// get scheduled events of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ScheduledEvents> GetNodeScheduledEventsAsync(this IHPCWebAPI operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetNodeScheduledEventsWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get events of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            public static IList<EventModel> GetNodeEvents(this IHPCWebAPI operations, string id)
            {
                return operations.GetNodeEventsAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get events of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<EventModel>> GetNodeEventsAsync(this IHPCWebAPI operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetNodeEventsWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get jobs of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            public static IList<NodeJob> GetNodeJobs(this IHPCWebAPI operations, string id)
            {
                return operations.GetNodeJobsAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get jobs of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<NodeJob>> GetNodeJobsAsync(this IHPCWebAPI operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetNodeJobsWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get metric history of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            public static NodeMetrics GetNodeMetricHistory(this IHPCWebAPI operations, string id)
            {
                return operations.GetNodeMetricHistoryAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get metric history of a node
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Node id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<NodeMetrics> GetNodeMetricHistoryAsync(this IHPCWebAPI operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetNodeMetricHistoryWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get node metric categories
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<string> GetMetricCategories(this IHPCWebAPI operations)
            {
                return operations.GetMetricCategoriesAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get node metric categories
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<string>> GetMetricCategoriesAsync(this IHPCWebAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetMetricCategoriesWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get node merics in a category
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='category'>
            /// </param>
            /// <param name='lastNodeId'>
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            public static Metrics GetMetricsOfCategory(this IHPCWebAPI operations, string category, string lastNodeId = default(string), int? count = 1000)
            {
                return operations.GetMetricsOfCategoryAsync(category, lastNodeId, count).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get node merics in a category
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='category'>
            /// </param>
            /// <param name='lastNodeId'>
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Metrics> GetMetricsOfCategoryAsync(this IHPCWebAPI operations, string category, string lastNodeId = default(string), int? count = 1000, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetMetricsOfCategoryWithHttpMessagesAsync(category, lastNodeId, count, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a list of clusruns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='lastId'>
            /// The object id since which(but not included) the objects are requested
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='reverse'>
            /// Get the results in reverse order
            /// </param>
            public static IList<Job> GetClusrunJobs(this IHPCWebAPI operations, int? lastId = default(int?), int? count = 1000, bool? reverse = false)
            {
                return operations.GetClusrunJobsAsync(lastId, count, reverse).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a list of clusruns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='lastId'>
            /// The object id since which(but not included) the objects are requested
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='reverse'>
            /// Get the results in reverse order
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Job>> GetClusrunJobsAsync(this IHPCWebAPI operations, int? lastId = default(int?), int? count = 1000, bool? reverse = false, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetClusrunJobsWithHttpMessagesAsync(lastId, count, reverse, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='job'>
            /// </param>
            public static Job CreateClusrunJob(this IHPCWebAPI operations, Job job = default(Job))
            {
                return operations.CreateClusrunJobAsync(job).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='job'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Job> CreateClusrunJobAsync(this IHPCWebAPI operations, Job job = default(Job), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateClusrunJobWithHttpMessagesAsync(job, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            public static Job GetClusrunJob(this IHPCWebAPI operations, int id)
            {
                return operations.GetClusrunJobAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Job> GetClusrunJobAsync(this IHPCWebAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetClusrunJobWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Cancel a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='job'>
            /// </param>
            public static void CancelClusrunJob(this IHPCWebAPI operations, int id, JobUpdate job = default(JobUpdate))
            {
                operations.CancelClusrunJobAsync(id, job).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Cancel a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='job'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task CancelClusrunJobAsync(this IHPCWebAPI operations, int id, JobUpdate job = default(JobUpdate), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.CancelClusrunJobWithHttpMessagesAsync(id, job, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Get aggregation result of a clusrun job
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            public static object GetClusrunJobAggregationResult(this IHPCWebAPI operations, int id)
            {
                return operations.GetClusrunJobAggregationResultAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get aggregation result of a clusrun job
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetClusrunJobAggregationResultAsync(this IHPCWebAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetClusrunJobAggregationResultWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get tasks of a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='lastId'>
            /// The object id since which(but not included) the objects are requested
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='requeueCount'>
            /// The number of times a job/task is requeued
            /// </param>
            public static IList<Models.Task> GetClusrunTasks(this IHPCWebAPI operations, int id, int? lastId = default(int?), int? count = 1000, int? requeueCount = default(int?))
            {
                return operations.GetClusrunTasksAsync(id, lastId, count, requeueCount).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get tasks of a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='lastId'>
            /// The object id since which(but not included) the objects are requested
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='requeueCount'>
            /// The number of times a job/task is requeued
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Models.Task>> GetClusrunTasksAsync(this IHPCWebAPI operations, int id, int? lastId = default(int?), int? count = 1000, int? requeueCount = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetClusrunTasksWithHttpMessagesAsync(id, lastId, count, requeueCount, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a task of a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='taskId'>
            /// Task id
            /// </param>
            public static Models.Task GetClusrunTask(this IHPCWebAPI operations, int id, int taskId)
            {
                return operations.GetClusrunTaskAsync(id, taskId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a task of a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='taskId'>
            /// Task id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Models.Task> GetClusrunTaskAsync(this IHPCWebAPI operations, int id, int taskId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetClusrunTaskWithHttpMessagesAsync(id, taskId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a task result of a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='taskId'>
            /// Task id
            /// </param>
            public static TaskResult GetClusrunTaskResult(this IHPCWebAPI operations, int id, int taskId)
            {
                return operations.GetClusrunTaskResultAsync(id, taskId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a task result of a clusrun
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='taskId'>
            /// Task id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TaskResult> GetClusrunTaskResultAsync(this IHPCWebAPI operations, int id, int taskId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetClusrunTaskResultWithHttpMessagesAsync(id, taskId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get the whole output of a task
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// Result key of a task
            /// </param>
            public static Stream GetClusrunOutput(this IHPCWebAPI operations, string key)
            {
                return operations.GetClusrunOutputAsync(key).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get the whole output of a task
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// Result key of a task
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Stream> GetClusrunOutputAsync(this IHPCWebAPI operations, string key, CancellationToken cancellationToken = default(CancellationToken))
            {
                var _result = await operations.GetClusrunOutputWithHttpMessagesAsync(key, null, cancellationToken).ConfigureAwait(false);
                _result.Request.Dispose();
                return _result.Body;
            }

            /// <summary>
            /// Get partial output of a task
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// Result key of a task
            /// </param>
            /// <param name='offset'>
            /// The distance from the beginning of the output
            /// </param>
            /// <param name='pageSize'>
            /// The size of requested piece of output
            /// </param>
            public static TaskOutput GetClusrunOutputInPage(this IHPCWebAPI operations, string key, int? offset = default(int?), int? pageSize = default(int?))
            {
                return operations.GetClusrunOutputInPageAsync(key, offset, pageSize).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get partial output of a task
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='key'>
            /// Result key of a task
            /// </param>
            /// <param name='offset'>
            /// The distance from the beginning of the output
            /// </param>
            /// <param name='pageSize'>
            /// The size of requested piece of output
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TaskOutput> GetClusrunOutputInPageAsync(this IHPCWebAPI operations, string key, int? offset = default(int?), int? pageSize = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetClusrunOutputInPageWithHttpMessagesAsync(key, offset, pageSize, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a list of diagnostic test runs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='lastId'>
            /// The object id since which(but not included) the objects are requested
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='reverse'>
            /// Get the results in reverse order
            /// </param>
            public static IList<Job> GetDiagnosticJobs(this IHPCWebAPI operations, int? lastId = default(int?), int? count = 1000, bool? reverse = false)
            {
                return operations.GetDiagnosticJobsAsync(lastId, count, reverse).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a list of diagnostic test runs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='lastId'>
            /// The object id since which(but not included) the objects are requested
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='reverse'>
            /// Get the results in reverse order
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Job>> GetDiagnosticJobsAsync(this IHPCWebAPI operations, int? lastId = default(int?), int? count = 1000, bool? reverse = false, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDiagnosticJobsWithHttpMessagesAsync(lastId, count, reverse, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='job'>
            /// </param>
            public static Job CreateDiagnosticJob(this IHPCWebAPI operations, Job job = default(Job))
            {
                return operations.CreateDiagnosticJobAsync(job).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='job'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Job> CreateDiagnosticJobAsync(this IHPCWebAPI operations, Job job = default(Job), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateDiagnosticJobWithHttpMessagesAsync(job, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            public static Job GetDiagnosticJob(this IHPCWebAPI operations, int id)
            {
                return operations.GetDiagnosticJobAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Job> GetDiagnosticJobAsync(this IHPCWebAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDiagnosticJobWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Cancel a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='job'>
            /// </param>
            public static void CancelDiagnosticJob(this IHPCWebAPI operations, int id, JobUpdate job = default(JobUpdate))
            {
                operations.CancelDiagnosticJobAsync(id, job).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Cancel a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='job'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task CancelDiagnosticJobAsync(this IHPCWebAPI operations, int id, JobUpdate job = default(JobUpdate), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.CancelDiagnosticJobWithHttpMessagesAsync(id, job, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Get aggregation result of a diagnostic job
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            public static object GetDiagnosticJobAggregationResult(this IHPCWebAPI operations, int id)
            {
                return operations.GetDiagnosticJobAggregationResultAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get aggregation result of a diagnostic job
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetDiagnosticJobAggregationResultAsync(this IHPCWebAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDiagnosticJobAggregationResultWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get tasks of a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='lastId'>
            /// The object id since which(but not included) the objects are requested
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='requeueCount'>
            /// The number of times a job/task is requeued
            /// </param>
            public static IList<Models.Task> GetDiagnosticTasks(this IHPCWebAPI operations, int id, int? lastId = default(int?), int? count = 1000, int? requeueCount = default(int?))
            {
                return operations.GetDiagnosticTasksAsync(id, lastId, count, requeueCount).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get tasks of a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='lastId'>
            /// The object id since which(but not included) the objects are requested
            /// </param>
            /// <param name='count'>
            /// Requested number of objects
            /// </param>
            /// <param name='requeueCount'>
            /// The number of times a job/task is requeued
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Models.Task>> GetDiagnosticTasksAsync(this IHPCWebAPI operations, int id, int? lastId = default(int?), int? count = 1000, int? requeueCount = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDiagnosticTasksWithHttpMessagesAsync(id, lastId, count, requeueCount, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a task of a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='taskId'>
            /// Task id
            /// </param>
            public static Models.Task GetDiagnosticTask(this IHPCWebAPI operations, int id, int taskId)
            {
                return operations.GetDiagnosticTaskAsync(id, taskId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a task of a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='taskId'>
            /// Task id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Models.Task> GetDiagnosticTaskAsync(this IHPCWebAPI operations, int id, int taskId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDiagnosticTaskWithHttpMessagesAsync(id, taskId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a task result of a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='taskId'>
            /// Task id
            /// </param>
            public static TaskResult GetDiagnosticTaskResult(this IHPCWebAPI operations, int id, int taskId)
            {
                return operations.GetDiagnosticTaskResultAsync(id, taskId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a task result of a diagnostic test run
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Job id
            /// </param>
            /// <param name='taskId'>
            /// Task id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TaskResult> GetDiagnosticTaskResultAsync(this IHPCWebAPI operations, int id, int taskId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDiagnosticTaskResultWithHttpMessagesAsync(id, taskId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get available diagnostic tests
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<DiagnoticTest> GetDiagnosticTests(this IHPCWebAPI operations)
            {
                return operations.GetDiagnosticTestsAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get available diagnostic tests
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<DiagnoticTest>> GetDiagnosticTestsAsync(this IHPCWebAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDiagnosticTestsWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get summary of nodes
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static NodeSummary GetNodeSummary(this IHPCWebAPI operations)
            {
                return operations.GetNodeSummaryAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get summary of nodes
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<NodeSummary> GetNodeSummaryAsync(this IHPCWebAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetNodeSummaryWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get summary of ClusRun jobs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static JobSummary GetClusRunJobSummary(this IHPCWebAPI operations)
            {
                return operations.GetClusRunJobSummaryAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get summary of ClusRun jobs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<JobSummary> GetClusRunJobSummaryAsync(this IHPCWebAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetClusRunJobSummaryWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get summary of diagnostic jobs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static JobSummary GetDiagnosticJobSummary(this IHPCWebAPI operations)
            {
                return operations.GetDiagnosticJobSummaryAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get summary of diagnostic jobs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<JobSummary> GetDiagnosticJobSummaryAsync(this IHPCWebAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDiagnosticJobSummaryWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Sync diagnostic and metric scripts from GitHub
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void SyncScripts(this IHPCWebAPI operations)
            {
                operations.SyncScriptsAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Sync diagnostic and metric scripts from GitHub
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task SyncScriptsAsync(this IHPCWebAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.SyncScriptsWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
